sudo: required
os: linux
dist: trusty
language: java

jobs:
  include:
  - name: Linux Oracle JDK 8
    jdk: oraclejdk8
  - name: Linux OpenJDK 8
    jdk: openjdk8
  - name: Linux OpenJDK 11
    jdk: openjdk11
  - name: Linux OpenJDK 13
    jdk: openjdk13